Add message listening system
httptoolkit/frida-js pull request #4
Opened 2024-05-13 21:01 UTC by Patrick-van-Halm

Adds the system to listen to Frida agent messages. Requires pull request: [Publicize setMethodCallHandler](https://github.com/httptoolkit/dbus-native/pull/1)

Resolves: #3

2024-05-13 21:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/httptoolkit/frida-js?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/httptoolkit/frida-js?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/httptoolkit/frida-js?pullRequest=4) it.</sub>

2024-05-14 16:26 UTC, pimterry requested changes
This is awesome! Thanks so much for looking into this, I've been meaning to investigate this for a while so this is super helpful.

A few comments here about the details but in general this looks great.

2024-05-14 16:26 UTC, pimterry commented on src/index.ts
> +                    return cb(JSON.parse(message[2]));
I'm not totally clear how the dbus message format works here, what the `=== 1` check is doing, or how we know `[2]` is always a message with `type: "send"`.

Is it possible to add a comment linking some docs for this format, or the corresponding Frida code defining it or similar?

A constant for the 1 that gives a hint at what it means (and what any non-1 values might mean) would also be helpful.

2024-05-14 16:26 UTC, pimterry commented on src/index.ts
> +                    return cb(JSON.parse(message[2]));
This `return` means we'll always only listen to the first message with the `message[0] === 1` in the batch. Is that correct?

2024-05-14 16:26 UTC, pimterry commented on test/test.spec.ts
> +            });
You can simplify this and remove the interval by moving the `listenToSession` code inside the promise, and calling resolve there directly with the message when it's received:

```javascript
const message = await new Promise<ScriptAgentMessage>((resolve, reject) => {
    fridaClient.listenToSession(id, resolve);
    setTimeout(() => {
        reject(new Error('Timed out waiting for message'));
    }, 5000);
});
```

2024-05-14 17:06 UTC, Patrick-van-Halm commented on src/index.ts
> +        return sessionId;
Yeah that sounds good. I wanted to do it like this but was a little hesitant with changing the code base too much haha

2024-05-14 17:07 UTC, Patrick-van-Halm commented on src/index.ts
> +                    return cb(JSON.parse(message[2]));
Ahh good one, I overlooked it myself last night. It should've been a continue statement.

2024-05-14 17:20 UTC, pimterry commented
I've now published dbus-native too, so you can update that here whenever you're ready.

By the way, in case you're not aware, [HTTP Toolkit Pro](https://httptoolkit.com/get-pro/) is totally free for all contributors to the every repo in this org, and this is already a very helpful contribution already! I've just set you up an account linked to your git email `pv...@gmail.com`. If that sounds useful, you can install HTTP Toolkit from [httptoolkit.com](https://httptoolkit.com), click 'Get Pro' then 'Log into existing account' and enter your email to use it.

2024-05-14 17:57 UTC, Patrick-van-Halm commented
> and this is already a very helpful contribution already! I've just set you up an account linked to your git email `pv...@gmail.com`. If that sounds

Thank you very much I will definitely look into it :)

2024-05-14 17:58 UTC, Patrick-van-Halm commented on package.json
> +    "prebuild": "rimraf dist/",
If you want I can revert this, but on windows it threw an error.

2024-05-15 15:32 UTC, Patrick-van-Halm commented
@pimterry Interesting how the CI fails on a different test every time. Could you take a look at the code? I applied the requested changes.

2024-05-15 16:17 UTC, pimterry commented
Yeah, I'm not sure what's happening there. There's definitely been some occasional flakiness in the past, but this seems very unusual. I'm going to do some more testing and see if I can get that fixed.

2024-05-16 13:26 UTC, pimterry requested changes
I've now fixed the tests on main and the seem to be much more reliable. I've rebased the PR and it's all passing :+1:

Thanks for those quick changes on this @Patrick-van-Halm! I've added a last couple of tiny comments here, but then I think this will be ready to merge.

2024-05-16 13:26 UTC, pimterry commented on src/index.ts
> +    type: MessageType,
I think this should be `MessageType.Send`

2024-05-16 13:26 UTC, pimterry commented on test/run-frida-server.ts
> +export const FRIDA_SERVER_BIN = path.join(FRIDA_SERVER_DIR, 'frida-server.exe');
I think this should be platform specific, just `.exe` for Windows

2024-05-17 16:37 UTC, pimterry approved these changes

2024-05-17 16:37 UTC, merged

2024-05-17 16:38 UTC, pimterry commented
Awesome! Thanks for all the hard work here, this is great :+1:. I'll do a release in just a sec.